<a href="https://colab.research.google.com/github/hardik-kumar-10/UCS420/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

marriage={
    'Tid':[1,2,3,4,5,6,7,8,9,10],
    'Refund':['yes','no','no','yes','no','no','yes','no','no','no'],
    'Martial Status': ['single','married','single','married','divorced','married','divorced','single','divorced','single'],
    'taxable income': ['125k','100k','70k','120k','95k','60k','220k','85k','75k','90k'],
    'cheat': ['no','no','no','no','yes','no','no','yes','no','yes']
}
df=pd.DataFrame(marriage)
print(df)

   Tid Refund Martial Status taxable income cheat
0    1    yes         single           125k    no
1    2     no        married           100k    no
2    3     no         single            70k    no
3    4    yes        married           120k    no
4    5     no       divorced            95k   yes
5    6     no        married            60k    no
6    7    yes       divorced           220k    no
7    8     no         single            85k   yes
8    9     no       divorced            75k    no
9   10     no         single            90k   yes

In [4]:
print(df.loc[0])
print('\n')
print(df.loc[4])
print('\n')
print(df.loc[7])
print('\n')
print(df.loc[8])
print('\n')

Tid                    1
Refund               yes
Martial Status    single
taxable income      125k
cheat                 no
Name: 0, dtype: object


Tid                      5
Refund                  no
Martial Status    divorced
taxable income         95k
cheat                  yes
Name: 4, dtype: object


Tid                    8
Refund                no
Martial Status    single
taxable income       85k
cheat                yes
Name: 7, dtype: object


Tid                      9
Refund                  no
Martial Status    divorced
taxable income         75k
cheat                   no
Name: 8, dtype: object

In [6]:
df.iloc[4:9,2:5]
print('\n')
df.iloc[ : ,1:4]

  Refund Martial Status taxable income
0    yes         single           125k
1     no        married           100k
2     no         single            70k
3    yes        married           120k
4     no       divorced            95k
5     no        married            60k
6    yes       divorced           220k
7     no         single            85k
8     no       divorced            75k
9     no         single            90k

In [2]:
import pandas as pd
path="/content/drive/MyDrive/Dataset/iris.csv"
df=pd.read_csv(path)
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [10]:
df.drop(df.columns[1],axis=1,inplace=True)
df.drop(1,axis=0,inplace=True)

IndexError: index 1 is out of bounds for axis 0 with size 1

In [11]:
df.head()

   sepal_length
0           5.1
2           4.7
3           4.6
4           5.0
5           5.4

In [13]:
import pandas as pd
path="/content/drive/MyDrive/Dataset/employees.csv"
df=pd.read_csv(path)

In [15]:
rows, cols = df.shape
print(f"Number of Rows: {rows}")
print(f"Number of Columns: {cols}")

Number of Rows: 5
Number of Columns: 10

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 528.0+ bytes

In [18]:
print(df.describe())

       Employee_ID        Age       Salary  Years_of_Experience   Bonus  \
count     5.000000   5.000000      5.00000             5.000000     5.0
mean    103.000000  34.000000  60000.00000             7.400000  5500.0
std       1.581139   5.612486   7905.69415             3.847077  1000.0
min     101.000000  28.000000  50000.00000             3.000000  4500.0
25%     102.000000  29.000000  55000.00000             4.000000  5000.0
50%     103.000000  34.000000  60000.00000             8.000000  5000.0
75%     104.000000  38.000000  65000.00000            10.000000  6000.0
max     105.000000  41.000000  70000.00000            12.000000  7000.0

         Rating
count  5.000000
mean   4.100000
std    0.494975
min    3.500000
25%    3.800000
50%    4.000000
75%    4.500000
max    4.700000

In [20]:
df.head()

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [24]:
df.tail(3)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [2]:
import pandas as pd
path="/content/drive/MyDrive/Dataset/employees.csv"
df=pd.read_csv(path)
avg_salary=df["Salary"].mean()
total_bonus=df["Bonus"].sum()
youngest_age=df["Age"].min()
highest_rating=df["Rating"].max()

print(f"Average Salary: {avg_salary}")
print(f"Average Salary: {total_bonus}")
print(f"Average Salary: {youngest_age}")
print(f"Average Salary: {highest_rating}")

Average Salary: 60000.0
Average Salary: 27500
Average Salary: 28
Average Salary: 4.7

In [4]:
df_sorted=df.sort_values(by="Salary",ascending=False)
print(df_sorted)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
3          104    Diana  Marketing   28   55000                    3
0          101    Alice         HR   29   50000                    4

  Joining_Date  Gender  Bonus  Rating
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
4   2010-11-25    Male   5000     3.5
3   2021-02-10  Female   4500     4.7
0   2020-03-15  Female   5000     4.5

In [5]:
def categorize_performance(rating):
  if rating>=4.5:
    return "excellent"
  elif rating>=4:
    return "Good"
  else:
    return "average"

df["Performance_Category"]=df["Rating"].apply(categorize_performance)

print(df)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating Performance_Category
0   2020-03-15  Female   5000     4.5            excellent
1   2017-07-19    Male   7000     4.0                 Good
2   2013-06-01    Male   6000     3.8              average
3   2021-02-10  Female   4500     4.7            excellent
4   2010-11-25    Male   5000     3.5              average

In [6]:
missing_values = df.isnull().sum()

print(missing_values)

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

In [7]:
df.rename(columns={"Employee_ID":"ID"})

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,average

In [11]:
count=0
for index, row in df.iterrows():
    if row["Years_of_Experience"] > 5:
        count += 1
        print(f"Employee: {row['Name']}, Experience: {row['Years_of_Experience']} years")

print("\nTotal Employees with more than 5 years of experience:", count)

Employee: Bob, Experience: 8 years
Employee: Charlie, Experience: 10 years
Employee: Edward, Experience: 12 years

Total Employees with more than 5 years of experience: 3

In [14]:
count=0
for index, row in df.iterrows():
    if row["Department"] == 'IT':
        count += 1
        print(f"Employee: {row['Name']}, Department: {row['Department']}")

print("\nTotal Employees with Department as IT:", count)

Employee: Bob, Department: IT
Employee: Charlie, Department: IT

Total Employees with Department as IT: 2

In [15]:
df["Tax"] = df["Salary"] * 0.10
print(df)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating Performance_Category     Tax
0   2020-03-15  Female   5000     4.5            excellent  5000.0
1   2017-07-19    Male   7000     4.0                 Good  7000.0
2   2013-06-01    Male   6000     3.8              average  6500.0
3   2021-02-10  Female   4500     4.7            excellent  5500.0
4   2010-11-25    Male   5000     3.5              average  6000.0

In [16]:
df.to_csv("employees_updated.csv", index=False)

print("Modified dataset saved as 'employees_updated.csv'")

Modified dataset saved as 'employees_updated.csv'